import type { CodegenConfig } from '@graphql-codegen/cli';

/**
 * Generates frontend types from the API's schema + our query documents.
 * The schema file is itself generated by NestJS (autoSchemaFile), so the chain is:
 *   API classes → schema.gql → generated/graphql.ts → web imports.
 * Any document field that drifts from the schema fails this build step.
 */
const config: CodegenConfig = {
  schema: '../../apps/api/src/schema.gql',
  documents: 'src/documents.ts',
  generates: {
    'src/generated/graphql.ts': {
      plugins: ['typescript-operations'],
      config: {
        skipTypename: false,
        useTypeImports: true,
      },
    },
  },
};

export default config;
